openapi: 3.1.0
info:
  title: BiDaR
  version: 1.0.0
paths:
  /semantic_web_data:
    post:
      requestBody:
        description: Users natural language querie
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/querie"
      responses:
        "200":
          description: Return a 200 status and a list containing querie results grouped as triples (data, relation, data)
  /query_all_data:
    post:
      requestBody:
        description: User Name
        content:
          application/json:
            schema:
              type: object 
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Return a 200 status and all data stored in application ontology connected to the user who's name was given
  /query_interests:
    post:
      requestBody:
        description: User Name
        content:
          application/json:
            schema:
              type: object 
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Return a 200 status and data queried from external sources, that is related to the user's interests
  /add_person:
    post:
      requestBody:
        description: Information about a new user in the system
        content:
          application/json:
            schema:
              type: object 
              properties:
                name:
                  type: string
                age:
                  type: integer
                gender:
                  type: string
                country:
                  type: string
                city:
                  type: string
                jobTitle:
                  type: string
                language:
                  type: string
                friends:
                  type: string
                interests:
                  type: string
                skills: 
                  type: string
                favoriteArtists:
                  type: string               
      responses:
        "200":
          description: Return a 200 status and all data stored in application ontology coresponding to the new user
  /get_all_persons:
    get:
      description: Returns a list containing the names of all the users in the application ontology
      responses:
        "200":
          description: Return a 200 status and the names of all the users in the application ontology
  /add_data:
    post:
      requestBody:
        description: reference to new data about an existing user, username, and the type of the new data
        content:
          application/json:
            schema:
              type: object 
              properties:
                name:
                  type: string
                data:
                  type: string
                section:
                  type: string
      responses:
        "200":
          description: Return a 200 status and the lable and externam data source reference to the newly added data
  /remove_data:
    post:
      requestBody:
        description: reference to existing data about an existing user, username, and the type of data
        content:
          application/json:
            schema:
              type: object 
              properties:
                name:
                  type: string
                data:
                  type: string
                section:
                  type: string
      responses:
        "200":
          description: Return a 200 status and True if data was deleted successfuly 
  /autocomplete_suggestions:
    post:
      requestBody:
        description: Partial name of a resource label and the type of resource
        content:
          application/json:
            schema:
              type: object 
              properties:
                input_text:
                  type: string
                type:
                  type: string
      responses:
        "200":
          description: Return a 200 status and a list of 10 sugestions of resources from the external data source that match the provided text