openapi: 3.1.0
info:
    title: API
    version: 1.0.0
webhooks:
    userPreferences:
        get:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"
            responses:
                "200":
                    description: User data retrieved successfully
                "404":
                    description: User was not found
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"
            responses:
                "200":
                    description: User data was successfully inserted/updated
                "401":
                    description: The requester is not authorized to modify the specified user
                    
    queryData:
        get:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Preference"
            responses:
                "200":
                    description: Query data retrieved successfully
                "404":
                    description: The preference was not found
                    
components:
    schemas:
        User:
            properties:
                id:
                    type: integer
                name:
                    type: string
                preferencesID:
                    type: integer
                    minItems: 1
                    maxItems: 10
                    uniqueItems: true
        Preference:
            properties:
                id:
                    type: integer
                name:
                    type: string
                
        